# Meta Data for SEO

## Homepage
title = "ODC"
titleSeparator = "-"
titleAddition = "OpenData Community"
description = "A place for the Web3 data community."

## Documentation
# docsVersion = "0.3"

## Open Graph
images = ["avatar.jpg"]
ogLocale = "en_US"
domainTLD = "spacetristan.github.io/opendataforweb3.github.io"
titleHome = "OpenData Community"

## Twitter Cards
twitterSite = "@OpenDataforWeb3"

## JSON-LD
schemaType = "Organization"
schemaName = "OpenDataforWeb3"
schemaAuthor = "OpenData Community"
schemaAuthorTwitter = "https://twitter.com/OpenDataforWeb3"
schemaAuthorGitHub = "https://github.com/OpenDataforWeb3/opendataforweb3.github.io"
schemaLocale = "en-US"
schemaLogo = "avatar.jpg"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "avatar.jpg"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/OpenDataforWeb3"
schemaGitHub = "https://github.com/OpenDataforWeb3/opendataforweb3.github.io"
schemaSection = "blog"

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

### Image template
defaultImage = "default-image.png" # put in `./assets/images/`
fillImage = "1270x740 Center" # normalize image size

# Footer
# footer = "Powered by <a class=\"text-muted\" href=\"https://www.netlify.com/\">Netlify</a>, <a class=\"text-muted\" href=\"https://gohugo.io/\">Hugo</a>, and <a class=\"text-muted\" href=\"https://getdoks.org/\">Doks</a>"


# Alert
alert = false
alertDismissable = true
# alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\" target=\"_blank\" rel=\"noopener\">Check out Doks v0.2</a>"
# alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\">Check out Doks v0.2</a>"

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
#repoHost = "Gitea"
docsRepo = "https://github.com/OpenDataforWeb3/opendataforweb3.github.io"
docsRepoBranch = "main"
# docsRepoSubPath = ""
editPage = false
lastMod = false

[sections]
  sectionNav = ["docs", "guides"]

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  searchSectionsShow = []
  searchSectionsIndex = []
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false
  multilingualMode = false
  docsVersioning = false
  fullWidth = false
  navbarSticky = true
  toTopButton = false
  scrollSpy = false # experimental; needs Bootstrap >= 5.2.0-beta1

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = true
