# baseURL = 'https://OpenDataforWeb3.github.io/'
languageCode = 'en-us'
languageName = "English"
title = 'Open Data for Web3'
theme = "beautifulhugo"
description = "Open Data for Web3"


[author]
    name = "SpaceTristan"
    github = "OpenDataforWeb3"
    twitter = "OpenDataforWeb3"
    discord = "OpenDataforWeb3"

[params]
    title = "Open Data for Web3"
    logo = "/avatar.jpg"
    favicon = "/favicon-16x16.png"

[params.header]
    [params.header.title]
        name = "Open Data for Web3"

#[[Params.bigimg]]
  #src = "/avatar.jpg"
  #desc = "Square"
  # position: see values of CSS background-position.
  # position = "center top"

# Menu config
[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = "Open Data for Web3"
  [[menu.main]]
    weight = 2
    identifier = "Hackathon"
    pre = ""
    post = ""
    name = "Hackathon"
    url = "/hackathon/"
    title = ""
  [[menu.main]]
    weight = 3
    identifier = "Learn"
    pre = ""
    post = ""
    name = "Learn"
    url = "/learn/"
    title = ""

[params.social]
  [params.social.Twitter]
    # weight when arranging icons (the greater the weight, the later the icon is positioned)
    weight = 0
    # your social ID
    id = "@OpenDataforWeb3"
    # prefix of your social link
    prefix = "https://twitter.com/"
    # content hovering on the icon
    title = "Twitter"
  [[params.social.Github]]
    # weight when arranging icons (the greater the weight, the later the icon is positioned)
    weight = 1
    # your social ID
    id = "@OpenDataforWeb3"
    # prefix of your social link
    prefix = "https://github.com/"
    # content hovering on the icon
    title = "Github"
   [[params.social.discord]]
    # weight when arranging icons (the greater the weight, the later the icon is positioned)
    weight = 1
    # your social ID
    id = "@OpenDataforWeb3"
    # prefix of your social link
    prefix = "https://discord.com/"
    # content hovering on the icon
    title = "Discord"


 # Home page config
[params.home]
  [params.home.profile]
    subtitle = "A place for the Web3 data community."

    avatarURL = "/avatar.jpg"


# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false

 